name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.config

trigger:
  branches:
    include:
    - master

variables:
- group: platform-global
- group: platform-dev
- group: platform-dev-samlclient

stages:
#build

- stage: build
  displayName: Build
  jobs: 
   - job: archivefolder
     steps:
      - task: CopyFiles@2
        displayName: Copy files for staging
        inputs:
          SourceFolder: $(Build.Repository.LocalPath)
          Contents: |
            app_data/**
            azure/**
            config/**
            node_modules/**
            src/**
            package.json
            process.json
            generate-certs.sh
          TargetFolder: $(System.DefaultWorkingDirectory)/Publish
          CleanTargetFolder: true

      - task: ArchiveFiles@1
        displayName: Archive build
        inputs:
          rootFolder: $(System.DefaultWorkingDirectory)/Publish
          includeRootFolder: true
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/samlclient-$(Build.BuildId).zip
          replaceExistingArchive: true
    
      - task: PublishPipelineArtifact@1
        displayName: Publish Pipeline Artifact
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)/samlclient-$(Build.BuildId).zip
          artifact: samlclient-$(Build.BuildId)
          publishLocation: 'pipeline'
