name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.config

trigger:
  branches:
    include:
    - master

variables:
- group: platform-global

stages:
#build
- stage: build
  displayName: Build
  jobs:
  - template: /Application/node/jobs/signin-master-build-job.yml@devopsTemplates
    parameters:
      applicationName: samlclient
      artifactName: samlclient-$(Build.BuildId)
      additionalFoldersForBuild: "ssl"

#Deploy
- stage: Deploy
  dependsOn: build
  displayName: Build
  jobs:
  - deployment: deployService
    displayName: Deploy SAML client
    environment: "dev"
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
            parameters:
              serviceConnection: $(devServiceConnection)
              subscriptionId: $(devSubscriptionId)
              resourceGroupName: $(projectId)d01-samlclient
              location: $(deploymentPrimaryLocation)
              templateFilePath: '$(Build.SourcesDirectory)/azure/template.json'
              armParameterOverrideString: '
                -appServiceName "$(projectId)d01-samlclient"
                -appServicePlanName "$(projectId)d01-samlclient-asp"
                -appServicePlanSku "{ "name": "S1", "tier": "Standard", "size": "S1", "family": "S", "capacity": 2}"
                -appServicePlanRG "$(projectId)d01-samlclient"
                -nodeVersion "14.5"
                -minTlsVersion "1.2"
                -numberOfWorkers 1
                -appInsightsInstrumentationKey "$(appInsightsInstrumentationKey)"
                -exclientBaseUrl "$(exclientBaseUrl)"
                -samlSigningCert "$(samlSigningCert)"
                -oidcHost "$(oidcHost)"
                -redisConn "$(redisConn)"
                -samlSigningCertRsaPrivateKey "$(samlSigningCertRsaPrivateKey)"
                -secretKeyBase "$(secretKeyBase)"
                -serviceID "$(serviceID)"
                -assertionsHost "$(assertionsHost)"
                -assertionsSecret "$(assertionsSecret)"
                -profileHost "$(profileHost)"
                -identityURL "$(identityURL)"'